[package]
name = "tmite"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tmite"
path = "src/main.rs"

[dependencies]
tmite-core.workspace = true
tmite-proto.workspace = true
clap = { version = "4", features = ["derive"] }
anyhow = "1"
dialoguer = "0.12"
console = "0.16"
ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }
n0-future = "0.3"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json.workspace = true
hex.workspace = true
iroh.workspace = true
